### ISSUE TITLE
Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by jpdhmc** [jpdhmc/encounter-tracker#1]
@pawaitemadisoncollege - Checkpoint 1 is ready for review.

**Comment by pawaitemadisoncollege** [comment]
Hi @jpdhmc! You have a fantastic start on your indie project. The list of user stories, problem statement, and screens show some careful thought and planning.

- [ ] One thing I like to double-check in this first checkpoint is that the MVP will hit the project requirements for the course.  Authentication is required, so you may want to mark the login user story as MVP, unless you are planning to demonstrate proficiency with that item in another way.
- [ ] Another requirement is implementing an api/service with java code. We'll learn how to do this in week 8, but I think it's a good idea to identify what service you are planning to use before that time and be sure to include it in a user story.  Again, you could choose to demonstrate this skill outside of your project if nothing fits in with your project goals.
- [ ] Your project plan is a bit on the sparse side. I recommend thinking about each user story and plan out when you hope to implement it (plans change, but it is a good idea to at least get down a first cut at this). Then, consider the pieces you will need to complete the various stories - which tables, jsps, java classes, etc?

I'm really looking forward to seeing some of the first classes and jsps here!
