### ISSUE TITLE
Peer Review 1 Form

### ISSUE THREAD

**Issue by pgfrank1** [jpdhmc/encounter-tracker#4]
# Project: Encounter-Tracker

### Problem Statement

1. John was able to describe the project's purpose.
2. No issues with grammar or typos.
3. He fully explained his problem and solution.
4. I think the average person would understand it. It depends on if they have played or heard of Dungeons and Dragons.

### Design Documentation

1. I was able to understand the flow of the application. It sounds like the design will be a fair bit different than what was shown. But John has the base "skeleton" of the application.
2. The values were shown in a logical fashion. They may have been designed a bit more for John himself, but John is the target audience for the application.
3. I couldn't see any form fields yet, but the only one would be for a new user as that is the only input data needed
4. I was able to see all the data that John wanted to present for his application and even mentioned a few new ones that could be included.

### Data model/Database

1. I couldn't see the design as he wrote it on a piece of paper. But it was quite a straightforward design that I was able to understand without even seeing the layout.
2. Yes, his database has a 1-to-many relationship.
3. Yes, his database is designed well and shouldn't encounter any dirty data.

### Code

1. Yes, his Maven structure is correct and understandable to any other user looking at it.
2. Yes, he has implemented a .gitignore file.
3. Yes, he has so far placed the head and header HTML tags in a JSP file to import them.
4. The Creature class itself has a ton of variables. I think he could split those up into their own classes such as Conditions and/or SpellSlot classes for remembering if a creature is poisoned or asleep. It would also help if there were a Player class in the future as they could utilize those classes as well.
5. Yes, he was using logging statements instead of println's.
6. Yes, for the entities and DAOs that currently exist. He has proper tests for each one.

**Comment by pawaitemadisoncollege** [comment]
Hi @pgfrank1 Thanks for your thoughtful review. 

I have one addition, there are a couple sneaky printstacktraces: 
![Screen Shot 2023-03-08 at 3 45 23 PM](https://user-images.githubusercontent.com/13874466/223857734-616a9a0f-4caa-4ba9-a925-00258d1a993e.png)
