### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by jpdhmc** [jpdhmc/encounter-tracker#5]
@pawaitemadisoncollege - Checkpoint 2 is ready for review.

**Comment by pawaitemadisoncollege** [comment]
Hi @jpdhmc! Your project is really coming along nicely!

**Checkpoint goals:**

1. Database designed and created - one change you will be able to make here (User table) after implementing Cognitos is that the password will not need to be stored in your database.

2. At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate and DAO is fully unit tested - the week 5 work was been completed here, so this was an easy one to cross off the list. That work paid off quickly! Remember to implement the GenericDao sooner than later to eliminate the redundant code in the existing daos. 

3. Log4J is implemented (no System.out.printlns) -printlns found in the Database class. A quick review shows log statements are present (to assist in tracking some of the actions in the UserDao for example).

4. Be sure to update your time log - as of right now the last entry was on 2/21. Your project plan still lacks a lot of detail - this is a very good time to document the individual tasks you have remaining to hit the mark over the next 8 weeks. Examples: add in when you will implement the DnD api; and when you will implement each of your user stories.

**Other**

I took a few minutes to look through other part of your project too:

- [ ] Current best practices tend to be to use jstl tags over directives if possible: https://github.com/jpdhmc/encounter-tracker/blob/03852b7826e50cf4e2e7fac71aa3f35dcef0d789/src/main/webapp/results.jsp#L5. We used the jstl import tag in Adv Java, for example. 
- [ ] This code will likely end up on many pages, https://github.com/jpdhmc/encounter-tracker/blob/03852b7826e50cf4e2e7fac71aa3f35dcef0d789/src/main/webapp/results.jsp#L1, so it is a good candidate for a jsp to be included on the various pages that need it.
- [ ] Consider using the jquery data table or a similar technique to add sorting and searching to your html tables.  Refer to the user display exercise solution for some sample code.
