### ISSUE TITLE
Checkpoint 3 complete

### ISSUE THREAD

**Issue by jpdhmc** [jpdhmc/encounter-tracker#7]
@pawaitemadisoncollege Checkpoint 3 is complete.

http://encountertracker-env.eba-w8kddmra.us-east-1.elasticbeanstalk.com/

**Comment by pawaitemadisoncollege** [comment]
Hi @jpdhmc! Congratulations on solidly hitting checkpoint 3!  I was able to sign up, log in, and display the users.  Well done!!!
